/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import niti.PrijemNit;

/**
 *
 * @author vujke
 */
public class KlijentGUI extends javax.swing.JFrame {
    Socket soket; 
            BufferedReader in;
            PrintStream out; 
            PrijemNit nit = null;
    /**
     * Creates new form KlijentGUI
     */
    public KlijentGUI() {
        try {
            initComponents();
            jlblbrObrisanijh.setVisible(false);
            soket = new Socket("localhost", 9000);
            out = new PrintStream(soket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(soket.getInputStream()));
        } catch (IOException ex) {
            Logger.getLogger(KlijentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtBrisi = new javax.swing.JButton();
        jlblIzbrisani = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblbrObrisanijh = new javax.swing.JLabel();
        jlblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtBrisi.setText("Obrisi karakter");
        jbtBrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrisiActionPerformed(evt);
            }
        });

        jlblIzbrisani.setText("Obrisani karakteri");

        jLabel1.setText("ukupno obrisanih:");

        jlblbrObrisanijh.setText("jLabel2");

        jlblStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblStatus.setText("IGRA JE U TOKU!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(jlblbrObrisanijh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtBrisi)
                            .addComponent(jlblIzbrisani, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jlblStatus)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbtBrisi)
                .addGap(46, 46, 46)
                .addComponent(jlblIzbrisani)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblbrObrisanijh))
                .addGap(53, 53, 53)
                .addComponent(jlblStatus)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrisiActionPerformed
        // TODO add your handling code here:
        
       
        if(nit ==null){
            nit = new PrijemNit(jlblIzbrisani, jlblbrObrisanijh, jlblStatus,in, out, soket, jbtBrisi);
        nit.start();
        }
        
         out.println("@");
        
    }//GEN-LAST:event_jbtBrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtBrisi;
    private javax.swing.JLabel jlblIzbrisani;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JLabel jlblbrObrisanijh;
    // End of variables declaration//GEN-END:variables
}
