/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.PrintStream;
import java.net.Socket;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import niti.KomNit;

/**
 *
 * @author vujke
 */
public class FrmKlijent extends javax.swing.JFrame {
    
    Socket soket;
    BufferedReader in;
    PrintStream out;
    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
        initComponents();
    }

    public FrmKlijent(Socket soket, BufferedReader in, PrintStream out){
        initComponents();
        this.soket = soket;
        this.in = in;
        this.out = out;
       /* this.jbtIzbaci = jbtIzbaci;
        this.jtxtIzbaci = jtxtIzbaci;
        this.jtxtPorukaServera = jtxtPorukaServera; */
       KomNit nit = new KomNit(soket, in, out, jtxtPorukaServera);
       nit.start();
    }
    
    

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtIzbaci = new javax.swing.JTextField();
        jbtIzbaci = new javax.swing.JButton();
        jtxtPorukaServera = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtIzbaci.setText("Izbaci");
        jbtIzbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIzbaciActionPerformed(evt);
            }
        });

        jtxtPorukaServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPorukaServeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jbtIzbaci, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIzbaci, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPorukaServera, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtxtIzbaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtIzbaci)
                .addGap(42, 42, 42)
                .addComponent(jtxtPorukaServera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPorukaServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPorukaServeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPorukaServeraActionPerformed

    private void jbtIzbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIzbaciActionPerformed
        // TODO add your handling code here:
        String pozicija = jtxtIzbaci.getText().trim();
        
        try{
            Integer.parseInt(pozicija);
            if(Integer.parseInt(pozicija)<1 || Integer.parseInt(pozicija) > 10) {
               JOptionPane.showMessageDialog(this, "Morate uneti celobrojnu vrednost od 1 do 10!");
               return;
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Morate uneti celobrojnu vrednost od 1 do 10!");
            return;
        }
        out.println(pozicija);
    }//GEN-LAST:event_jbtIzbaciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlijent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtIzbaci;
    private javax.swing.JTextField jtxtIzbaci;
    private javax.swing.JTextField jtxtPorukaServera;
    // End of variables declaration//GEN-END:variables
}
