/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import niti.ServerNit;

/**
 *
 * @author vujke
 */
public class ServerGUI extends javax.swing.JFrame {
    
    List<Integer> listaBrojeva =  new ArrayList<>();
    ServerNit nit = new ServerNit(listaBrojeva);
    Boolean susp = false;

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
        jtxtUnetiBrojevi.setEditable(false);
        jbtZaustaviServer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtBroj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtUnetiBrojevi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtUnesiBroj = new javax.swing.JButton();
        jbtPokreniServer = new javax.swing.JButton();
        jbtZaustaviServer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBrojActionPerformed(evt);
            }
        });

        jLabel1.setText("Broj:");

        jLabel2.setText("Uneti brojevi:");

        jbtUnesiBroj.setText("Unesi broj");
        jbtUnesiBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUnesiBrojActionPerformed(evt);
            }
        });

        jbtPokreniServer.setText("Pokreni server");
        jbtPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPokreniServerActionPerformed(evt);
            }
        });

        jbtZaustaviServer.setText("Zaustavi server");
        jbtZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtZaustaviServerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Server program nije pokrenut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtUnesiBroj))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUnetiBrojevi, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jbtUnesiBroj)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUnetiBrojevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtPokreniServer)
                    .addComponent(jbtZaustaviServer))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBrojActionPerformed

    private void jbtUnesiBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUnesiBrojActionPerformed
        // TODO add your handling code here:
        int broj;
        try{
            broj = Integer.parseInt(jtxtBroj.getText());
        }catch( Exception ex){
            JOptionPane.showMessageDialog(rootPane, "niste uneli br");
            return;
        }
        
        if(validan(broj)){
        jtxtUnetiBrojevi.setText(jtxtUnetiBrojevi.getText()+" "+broj);
        listaBrojeva.add(broj);
        
        } else {
            JOptionPane.showMessageDialog(rootPane, "ne moze vise od 2 puta isti broj");
        }
        
    }//GEN-LAST:event_jbtUnesiBrojActionPerformed

    private void jbtPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPokreniServerActionPerformed
        // TODO add your handling code here:
        if (listaBrojeva.size() == 4){
            //ServerNit nit = new ServerNit(listaBrojeva);
            if(!isSuspended()){
                nit.start();
                System.out.println("server pokrenut");
            } else {
                nit.resume();
                System.out.println("server opet pokrenut");
                susp = false;
            }
            
            jLabel3.setText("<html><font color=green>Server je pokrenut</font></html>");
            jbtZaustaviServer.setVisible(true);
            jbtUnesiBroj.setEnabled(false);
            jbtPokreniServer.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Mora da bude tacno 4 broja uneto");
        }
    }//GEN-LAST:event_jbtPokreniServerActionPerformed

    private void jbtZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtZaustaviServerActionPerformed
        // TODO add your handling code here:
            nit.suspend();
            System.out.println("server ugasen");
            susp = true;
            jLabel3.setText("<html><font color=red>Server nije pokrenut!</font></html>");
            jbtUnesiBroj.setEnabled(true);
            jbtPokreniServer.setEnabled(true);
    }//GEN-LAST:event_jbtZaustaviServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtPokreniServer;
    private javax.swing.JButton jbtUnesiBroj;
    private javax.swing.JButton jbtZaustaviServer;
    private javax.swing.JTextField jtxtBroj;
    private javax.swing.JTextField jtxtUnetiBrojevi;
    // End of variables declaration//GEN-END:variables

    private boolean validan(int broj) {
        int brojac = 0;
        for (Integer br : listaBrojeva) {
            if(br == broj) brojac++;
        }
        
        if(brojac < 2){
            return true;
        }else{
            return false;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean isSuspended() {
        if(susp){
            return true;
        } else{
            return false;
        } 
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
