/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import niti.PrijemNit;

/**
 *
 * @author vujke
 */
public class KlijentLogin extends javax.swing.JFrame {
    
    int brPokusaja = 0;
    List<String> koriscenaSlova = new ArrayList<>();
    Socket soket = null;
    BufferedReader in;
    PrintStream out;
    boolean kraj = false;
    /**
     * Creates new form KlijentLogin
     */
    public KlijentLogin() {
        initComponents();
        jbtIzaberi.setEnabled(false);
        jbtPogodi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblServer = new javax.swing.JLabel();
        jlblSlova = new javax.swing.JLabel();
        jlblPokusaji = new javax.swing.JLabel();
        jbtPogodi = new javax.swing.JButton();
        jtxtSlovo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jbtIzaberi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jbtLogin.setText("Log in");
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtLogin))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jbtLogin)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblServer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblServer.setText("****");

        jlblSlova.setText("Koriscena slova: ");

        jlblPokusaji.setText("Broj pokusaja: ");

        jbtPogodi.setText("Pogodi");
        jbtPogodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPogodiActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EVRO gradovi", "Predmeti na FON-u ", "fudbalski timovi Srbije" }));

        jbtIzaberi.setText("Izaberi");
        jbtIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtPogodi)
                                .addGap(32, 32, 32)
                                .addComponent(jtxtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPokusaji, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jlblServer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jbtIzaberi)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtIzaberi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblSlova)
                .addGap(18, 18, 18)
                .addComponent(jlblPokusaji)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtPogodi)
                    .addComponent(jtxtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
        // TODO add your handling code here:
        String email = jtxtUser.getText().trim();
        String pass = jtxtPass.getText().trim();
        
            int validBr = valid(email, pass);
            
            switch(validBr){
                case 0: JOptionPane.showMessageDialog(rootPane, "Sve ok");
                break;
                case 1: JOptionPane.showMessageDialog(rootPane, "fali @");
                break;
                case 2: JOptionPane.showMessageDialog(rootPane, "nije dobra sifra");
                break;
                case 4: JOptionPane.showMessageDialog(rootPane, "greska");
                break;
                default: JOptionPane.showMessageDialog(rootPane, "Greska");
                break;
            }
            
            if(validBr == 0){
            try {
                soket = new Socket("localhost", 9000);
                in = new BufferedReader(new InputStreamReader(soket.getInputStream()));
                out = new PrintStream(soket.getOutputStream());
                String kredencijali = "###"+email+"/"+pass;
                out.println(kredencijali);
                
                String odgovor = in.readLine();
            while (true) {
                System.out.println(odgovor);
                if (odgovor.startsWith("ne")) {
                    JOptionPane.showMessageDialog(this, "Pogresno korisnicko ime!");
                    //korisnik = jtxtKorisnik.getText().trim();
                    return;
                } else if(odgovor.startsWith("ok")) {
                    //JOptionPane.showMessageDialog(this, odgovor);
                    jPanel1.setVisible(false);
                    jbtIzaberi.setEnabled(true);
                    jbtPogodi.setEnabled(true);
                    return;
                }else {
                    break;
                }
            }
            } catch (IOException ex) {
                //Logger.getLogger(KlijentLogin.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showConfirmDialog(rootPane, "Otkacen klijent");
            }
            }
        
        
    }//GEN-LAST:event_jbtLoginActionPerformed

    private void jbtIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIzaberiActionPerformed
        // TODO add your handling code here:
        int kategorija =  jComboBox1.getSelectedIndex();
        
        out.println(kategorija);
        PrijemNit nit = new PrijemNit(soket, in, out, jlblServer, kraj);
        nit.start();
        //String odgovor = in.readLine();
        
    }//GEN-LAST:event_jbtIzaberiActionPerformed

    private void jbtPogodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPogodiActionPerformed
        // TODO add your handling code here:
        String slovo = jtxtSlovo.getText();
        if(slovo.length() >1){
            JOptionPane.showConfirmDialog(rootPane, "samo jedno slovo!");
            
        }else{
            
            if(koriscenaSlova.contains(slovo)){
                JOptionPane.showMessageDialog(rootPane, "vec ima to slovo");
            }else{
                koriscenaSlova.add(slovo);
            jlblSlova.setText(koriscenaSlova.toString());
            out.println(slovo);
            brPokusaja++;
            jlblPokusaji.setText(jlblPokusaji.getText()+" "+brPokusaja);
            if(brPokusaja == jlblServer.getText().length()+8){
                jbtPogodi.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "Nema vise pokusaja");
            }
            }
            
        }
        
        
    }//GEN-LAST:event_jbtPogodiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtIzaberi;
    private javax.swing.JButton jbtLogin;
    private javax.swing.JButton jbtPogodi;
    private javax.swing.JLabel jlblPokusaji;
    private javax.swing.JLabel jlblServer;
    private javax.swing.JLabel jlblSlova;
    private javax.swing.JTextField jtxtPass;
    private javax.swing.JTextField jtxtSlovo;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables

    private int valid(String email, String pass) {
        
        try {
          if(!email.contains("@")){
            return 1;//JOptionPane.showMessageDialog(rootPane, "Fali @");
            }
            char c = pass.toLowerCase().charAt(0);
            if(!(c >= 'a' && c <= 'z') || !pass.matches(".*\\d.*")){
               return 2;// JOptionPane.showMessageDialog(rootPane, "Mora poceti slovom i sadrzati bar jedan broj");
            }  
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(rootPane, "Greska!");
            return 4;
        }
          return 0;  
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
